# Generated by Django 4.0.10 on 2023-03-30 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_book', '0001_order_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBookStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.IntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Monthly')], default=0)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('average_price', models.FloatField()),
                ('total_volume', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
