# Generated by Django 4.0.10 on 2023-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_book', '0002_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbookstatistics',
            name='period_type',
            field=models.IntegerField(choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly')], default=0),
        ),
    ]
