# Generated by Django 4.0.10 on 2023-04-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_book', '0003_alter_orderbookstatistics_period_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='avg_24h',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='change_24h',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='high_24h',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='low_24h',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='volume_24h',
        ),
    ]
